name: 'FixFlow'
description: 'Automatically create MNEE bounties for failing tests'
author: 'FixFlow Team'

branding:
  icon: 'dollar-sign'
  color: 'green'

inputs:
  bounty_amount:
    description: 'Default bounty amount in MNEE (can be overridden by config)'
    required: false
    default: '50'
  
  max_bounty:
    description: 'Maximum bounty amount after escalation'
    required: false
    default: '150'
  
  config_file:
    description: 'Path to bounty configuration file'
    required: false
    default: '.fixflow.yml'
  
  on_failure_only:
    description: 'Only trigger on test failures'
    required: false
    default: 'true'
  
  github_token:
    description: 'GitHub token for API access'
    required: true
  
  bot_server_url:
    description: 'URL of the FixFlow bot server'
    required: true
  
  bot_api_key:
    description: 'API key for authenticating with the bot'
    required: true
  
  aws_access_key_id:
    description: 'AWS Access Key ID for Amazon Bedrock'
    required: true
  
  aws_secret_access_key:
    description: 'AWS Secret Access Key for Amazon Bedrock'
    required: true
  
  aws_region:
    description: 'AWS Region for Amazon Bedrock (e.g., us-east-1)'
    required: false
    default: 'us-east-1'
  
  bedrock_model_id:
    description: 'Amazon Bedrock model ID to use for analysis'
    required: false
    default: 'anthropic.claude-3-sonnet-20240229-v1:0'

outputs:
  bounty_created:
    description: 'Whether a bounty was created'
  
  bounty_id:
    description: 'ID of the created bounty'
  
  issue_number:
    description: 'GitHub issue number created'
  
  issue_url:
    description: 'URL of the created issue'

runs:
  using: 'node20'
  main: 'dist/index.js'