name: FixFlow - Automated Bug Bounties with AI Analysis

on:
  workflow_run:
    workflows: ["Tests", "CI", "Build"]  # Names of your test workflows
    types:
      - completed

jobs:
  create-bounty:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Create Bounty for Failed Tests
        uses: fixflow/fixflow-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          bot_server_url: https://api.fixflow.io  # Or your self-hosted instance
          bounty_amount: 50  # Default amount in MNEE
          max_bounty: 150   # Maximum after escalation
          config_file: .fixflow.yml
        id: bounty
      
      - name: Bounty Created Summary
        if: steps.bounty.outputs.bounty_created == 'true'
        run: |
          echo "✅ Bounty created successfully!"
          echo "Issue: ${{ steps.bounty.outputs.issue_url }}"
          echo "Bounty ID: ${{ steps.bounty.outputs.bounty_id }}"
          echo "AI Analysis: ${{ steps.bounty.outputs.ai_error_type }} (${{ steps.bounty.outputs.ai_complexity }} complexity)"

# Alternative: Trigger on push/PR with test job
---
name: Tests with FixFlow AI Analysis

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run tests
        run: npm test
        continue-on-error: true
        id: test
      
      - name: Create Bounty on Test Failure
        if: steps.test.outcome == 'failure'
        uses: fixflow/fixflow-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          bot_server_url: https://api.fixflow.io
          bounty_amount: 50
          on_failure_only: true

# Example with custom configuration
---
name: Custom Bounty Configuration

on:
  workflow_dispatch:
    inputs:
      bounty_amount:
        description: 'Bounty amount in MNEE'
        required: false
        default: '75'

jobs:
  test-and-bounty:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Run integration tests
        run: |
          ./scripts/run-integration-tests.sh
        continue-on-error: true
        id: integration-tests
      
      - name: Create Custom Bounty with AI Analysis
        if: steps.integration-tests.outcome == 'failure'
        uses: fixflow/fixflow-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          bot_server_url: https://api.fixflow.io
          bounty_amount: ${{ github.event.inputs.bounty_amount || '75' }}
          max_bounty: 300  # Higher max for integration tests

# ============================================================================
# NO SECRETS REQUIRED!
# ============================================================================
# The FixFlow GitHub Action uses your repository's built-in GITHUB_TOKEN
# for authentication. No additional secrets are needed!
#
# The GITHUB_TOKEN proves the action has access to the repository,
# which the FixFlow bot server verifies before creating bounties.
#
# For self-hosted FixFlow servers, you may need to set:
# - FIXFLOW_SERVER_URL - URL of your self-hosted instance
#
# ============================================================================
# HOW IT WORKS
# ============================================================================
# 1. When your tests fail, the GitHub Action detects the failure
# 2. It uses your GITHUB_TOKEN to authenticate with the FixFlow bot server
# 3. The bot server verifies the token has access to your repository
# 4. AI-powered analysis is performed using Amazon Bedrock (server-side)
# 5. A GitHub issue is created with:
#    - Detailed AI analysis of the root cause
#    - Suggested fixes with code examples
#    - Bounty amount and claiming instructions
# 6. When someone fixes the issue and their PR is merged, they get paid!
#
# ============================================================================
# OUTPUTS
# ============================================================================
# The action provides these outputs for use in subsequent steps:
#
# - bounty_created: 'true' or 'false'
# - bounty_id: The unique ID of the created bounty
# - issue_number: The GitHub issue number
# - issue_url: URL to the created issue
# - ai_error_type: AI-detected error type (e.g., "Assertion Error")
# - ai_complexity: AI-estimated fix complexity (easy/medium/hard)